import azure.functions as func
import json
import logging
import os
from typing import Dict, Any
from datetime import datetime
from github import Github, GithubException

# Initialize logging
logger = logging.getLogger(__name__)

# Environment variables
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "kvna/iac-docs-ai")


def main(req: func.HttpRequest) -> func.HttpResponse:
    """
    HTTP trigger function that creates a GitHub Pull Request with AI-suggested improvements.
    """
    logger.info('Create PR function triggered')

    # Handle CORS preflight
    if req.method == "OPTIONS":
        return func.HttpResponse(
            status_code=204,
            headers={
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "POST, OPTIONS",
                "Access-Control-Allow-Headers": "Content-Type",
            }
        )

    # Validate environment variables
    if not GITHUB_TOKEN:
        logger.error("Missing GITHUB_TOKEN environment variable")
        return create_error_response(
            "Server configuration error",
            500,
            "GitHub authentication not configured"
        )

    try:
        # Parse request body
        req_body = req.get_json()
        document_id = req_body.get('document_id', '').strip()
        suggestions = req_body.get('suggestions', {})

        if not all([document_id, suggestions]):
            return create_error_response(
                "Missing required fields",
                400,
                "document_id and suggestions are required"
            )

        logger.info(f"Creating PR for document: {document_id}")

        # Extract suggestion data
        modified_frontmatter = suggestions.get('modified_frontmatter', '')
        modified_content = suggestions.get('content_changes', {}).get('modified_content', '')
        explanation = suggestions.get('explanation', '')
        content_summary = suggestions.get('content_changes', {}).get('summary', '')
        metadata_summary = suggestions.get('metadata_changes', {}).get('summary', '')

        if not modified_frontmatter or not modified_content:
            return create_error_response(
                "Invalid suggestions format",
                400,
                "Modified frontmatter and content are required"
            )

        # Create full document with frontmatter
        full_document = f"---\n{modified_frontmatter}\n---\n\n{modified_content}"

        # Initialize GitHub client
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(GITHUB_REPO)

        # Determine file path
        file_path = determine_file_path(repo, document_id)
        if not file_path:
            return create_error_response(
                "Document not found in repository",
                404,
                f"Could not locate file for: {document_id}"
            )

        logger.info(f"File path determined: {file_path}")

        # Create branch name
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        branch_name = f"ai-improve-{document_id}-{timestamp}"

        # Get default branch
        default_branch = repo.default_branch
        base_branch = repo.get_branch(default_branch)

        # Create new branch
        logger.info(f"Creating branch: {branch_name}")
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=base_branch.commit.sha
        )

        # Update file in new branch
        logger.info(f"Updating file: {file_path}")
        file_contents = repo.get_contents(file_path, ref=default_branch)

        commit_message = f"AI-suggested improvements to {document_id}\n\n{explanation}"

        repo.update_file(
            path=file_path,
            message=commit_message,
            content=full_document,
            sha=file_contents.sha,
            branch=branch_name
        )

        # Create Pull Request
        logger.info("Creating pull request")

        pr_title = f"🤖 AI Improvements: {document_id}"

        pr_body = f"""## AI-Suggested Documentation Improvements

### Document
**{document_id}**

### Summary
{explanation}

### Content Changes
{content_summary}

### Metadata Changes
{metadata_summary}

---

### Review Checklist
- [ ] Content changes are accurate and helpful
- [ ] Metadata improvements enhance searchability
- [ ] Code examples are correct (if applicable)
- [ ] Links and references are valid
- [ ] Formatting is consistent with style guide

---

*This pull request was automatically generated by AI based on user feedback.*
*Please review carefully before merging.*

**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")}
"""

        pull_request = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=default_branch
        )

        # Add labels
        try:
            pull_request.add_to_labels("ai-suggested", "documentation")
        except GithubException as e:
            logger.warning(f"Could not add labels (they may not exist): {str(e)}")

        logger.info(f"Successfully created PR: {pull_request.html_url}")

        # Prepare response
        response_data = {
            "success": True,
            "pr_url": pull_request.html_url,
            "pr_number": pull_request.number,
            "branch_name": branch_name
        }

        return func.HttpResponse(
            body=json.dumps(response_data),
            status_code=200,
            headers={
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*"
            }
        )

    except GithubException as e:
        logger.error(f"GitHub API error: {str(e)}")
        return create_error_response(
            "GitHub API error",
            500,
            str(e)
        )

    except ValueError as e:
        logger.error(f"Invalid request: {str(e)}")
        return create_error_response("Invalid request format", 400, str(e))

    except Exception as e:
        logger.error(f"Error creating PR: {str(e)}", exc_info=True)
        return create_error_response(
            "An error occurred while creating the pull request",
            500,
            str(e)
        )


def determine_file_path(repo, document_id: str) -> str:
    """Determine the file path for a document in the repository."""
    # Extract document type from ID
    doc_type = document_id.split('-')[0] if '-' in document_id else ''

    # Map document types to directories
    type_to_dir = {
        'concept': 'day1',
        'howto': 'week1-4',
        'reference': 'reference',
        'troubleshooting': 'troubleshooting',
        'lpath': 'learning-paths'
    }

    # Get likely directory
    directory = type_to_dir.get(doc_type, 'day1')

    # Possible paths to check
    possible_paths = [
        f"docs/{directory}/{document_id}.md",
        f"docs/day1/{document_id}.md",
        f"docs/week1-4/{document_id}.md",
        f"docs/month1-2/{document_id}.md",
        f"docs/learning-paths/{document_id}.md",
        f"docs/reference/{document_id}.md",
        f"docs/troubleshooting/{document_id}.md"
    ]

    # Try to find the file
    for path in possible_paths:
        try:
            repo.get_contents(path)
            logger.info(f"Found file at: {path}")
            return path
        except GithubException:
            continue

    logger.error(f"File not found for document: {document_id}")
    return None


def create_error_response(message: str, status_code: int, detail: str = None) -> func.HttpResponse:
    """Create a standardized error response."""
    error_data = {
        "error": message
    }
    if detail:
        error_data["detail"] = detail

    return func.HttpResponse(
        body=json.dumps(error_data),
        status_code=status_code,
        headers={
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*"
        }
    )
